name: Automated Builds
on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - build.gradle
      - gradle.properties
      - settings.gradle
      - gradle/**
      - gradlew
      - gradlew.bat
      - versioning.gradle
      - .github/workflows/publish-devbuilds.yml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      
    - name: Run datagen
      run: ./gradlew runDatagen
      
    - name: Build
      run: ./gradlew build
      
    - name: Publish artifacts
      uses: drtheodor/discord-webhook-upload-action@v0.2
      with:
        url: ${{ secrets.EXTRAS_DEV_BUILDS }}
        username: george addington
        avatar: 'https://i.imgur.com/PLXp29k.png'
        
        message_commit: '> :sparkles: [${commitMessage}](<${commitUrl}>) by [${authorName}](<${authorUrl}>)'
        message_header: |
          <:new1:1253371736510959636><:new2:1253371805734015006> New `Adventures in Time: Extras` dev build `#${{ github.run_number }}`:

        file: 'build/libs/*'
        
    - name: Setup Amble Maven
      id: setup-maven
      uses: drtheodor/static-file-server-actions/upload/setup@main
      with:
        repo: Addi3/maven

    - name: Build for Maven
      env:
        CI_MAVEN_PATH: ${{ steps.setup-maven.outputs.path }}
      run: ./gradlew publishMavenJavaPublicationToCiRepository

    - name: Publish to Amble Maven
      uses: drtheodor/static-file-server-actions/upload@main
      with:
        published: com/aitextras
        token: ${{ secrets.PAT_TOKEN }}
        message: "chore: publish AIT Extras artifacts"
